### ISSUE TITLE
EP_AddEpochsFromStimSetNote fails on TestPulse stimsets, RTE is silently cleared

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#1063]
With TP during DAQ there exist stimsets containing testpulses.

EP_AddEpochsFromStimSetNote is called for these stimsets as well, but the stimset has no wave note.

This is not checked properly, whereas in MIES_Epochs.ipf a RTE is generated (epochCount = NaN) and the following code adds wrong epoch information to the TestPulse stimset. (Stimset Baseline / ST_B)
https://github.com/AllenInstitute/MIES/blob/c5830c7b870ea6d371da9d7a4e06a1cd892edc81/Packages/MIES/MIES_Epochs.ipf#L182

This RTE is silently cleared later by DC_PrepareLBNEntries where str2numSafe is used.
https://github.com/AllenInstitute/MIES/blob/c5830c7b870ea6d371da9d7a4e06a1cd892edc81/Packages/MIES/MIES_DataConfigurator.ipf#L975

How should we handle this?

- Should EP_AddEpochsFromStimSetNote ignore stimsets without wavenote?
- Should we detect if the stimset is a test pulse and not call EP_AddEpochsFromStimSetNote then / Assert out on empty wave note in the function then?
- Are the wrong epochs a problem with already present data?

- Silently clearing a RTE should not happen. In the routines that clear RTEs on purpose ASSERTs should be added before that catch pending RTEs.

**Comment by t-b** [comment]
RTE clearing happens also in https://github.com/AllenInstitute/MIES/blob/c5830c7b870ea6d371da9d7a4e06a1cd892edc81/Packages/MIES/MIES_DataConfigurator.ipf#L799. I don't remember why we did that,

> Should EP_AddEpochsFromStimSetNote ignore stimsets without wavenote?

Yes it should ignore stimsets without wavenote. "Third party" stimsets don't need have a special wave note as well. A third party stimset is one which does not have all three parameter waves.

So all simsets for which `WB_StimsetIsFromThirdParty(stimset) || !cmpstr(stimset, STIMSET_TP_WHILE_DAQ)` is true will not have epoch info from the stimset note. And we should, for now, also not have epoch info for `TP during DAQ channels at all, as that needs to be figured out properly on its own, see https://github.com/AllenInstitute/MIES/issues/958.
 
> Are the wrong epochs a problem with already present data?

I don't think so, TP during DAQ is quite an exotic feature still. Nethertheless a fix should increase `SWEEP_EPOCH_VERSION` so that we have it documented.

> Silently clearing a RTE should not happen. In the routines that clear RTEs on purpose ASSERTs should be added before that catch pending RTEs.

Yes unfortuantely, this is the way to go. It would be nice if IP would be more helpful here though.
