### ISSUE TITLE
Hide failed sweeps from PA plot

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#151]
- [x] Checkbox for enabling
- [x] Checkbox for hiding traces without level
- [x] SetVariable for level
- [x] Findlevel on pulses on diagonal (before zeroing). Those without level are color coded red (or hidden depending on checkbox) and the pulses from the same region/sweep/pulse/channelType as well.
- [x] Ignore for average
- [x] Mark the trace set which contains a failed sweep somehow

**Comment by t-b** [comment]
- [ ] Add a new column to the OVS listbox to enter the pulses
- [ ] The "headstage removal" checkbox should be generalized
- [ ] Convert the PA code to gather all info from a struct/wave instead of the getting tracedata from the databrowser/sweepbrowser graph. After this change the PA code should not read from this graph anymore.

**Comment by timjarsky** [comment]
> * [ ]  Add a new column to the OVS listbox to enter the pulses
> * [ ]  The "headstage removal" checkbox should be generalized
> * [ ]  Convert the PA code to gather all info from a struct/wave instead of the getting tracedata from the databrowser/sweepbrowser graph. After this change the PA code should not read from this graph anymore.

@t-b instead of doing the above, using a spike filter should resolve the main issue for removing traces from overlay sweeps.
