### ISSUE TITLE
JSON Configuration: Allow configuration of unassociated AD/DA channels

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1763]
Test "UnassociatedChannelsAndTTLs"

**Comment by MichaelHuth** [comment]
I have tested around and it seems to work properly.

I ran the test, then saved the DAEphys configuration, closed it and restored the configuration.

Then I acquire one sweep as the test does and the result is identical.

Here the recipe:
```
runwithopts(testcase="UnassociatedChannelsAndTTLs")
CONF_SaveWindow("C:projects:daephys.json")

```
close the panel

`CONF_RestoreWindow("C:projects:daephys.json", usePanelTypeFromFile=1)`

Acquire again.

@t-b if that works for you too, I would say we can close this issue.

**Comment by timjarsky** [comment]
@t-b @MichaelHuth I can confirm this works.

**Comment by timjarsky** [comment]
@t-b  I ran into this again when testing TP insertion into unassociated DA channels. I'm finding that the amplifier hardware settings are getting instantiated on configuration. So, when checking DA2, for example, headstage 2 gets activated rather than only (unassociated) DA2. This happens despite having cleared the associations for that headstage: 
![image](https://github.com/AllenInstitute/MIES/assets/5693697/61f22e00-cb5f-4fc8-9405-cd7019cad26b)

I also see a potentially related issue with `save window configuration` where MIES asks the user to select an existing file rather than save it with a new name.

**Comment by t-b** [comment]
There is something odd with the config for unassoc.

> I also see a potentially related issue with save window configuration where MIES asks the user to select an existing file rather than save it with a new name.

I saw that as well, moved to #1801.
