### ISSUE TITLE
CI: DeployReports jobs fails on release branch

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1847]
See https://github.com/AllenInstitute/MIES/actions/runs/5813883834/job/15777096787

I don't think that job should run there.

**Comment by t-b** [comment]
Please make a PR against release/2.7 and a forwardport against main.

**Comment by Garados007** [comment]
It took a while but I found the problem.

The job `GenerateReports` cannot succeed because there is no `Cobertura_*.xml` file generated. To create these, the variable `do_instrumentation` for `CallPR` in `build-release.yml` needs to be set to `1`. This is only done if the current reference branch is the `main` branch.

https://github.com/AllenInstitute/MIES/blob/6c868a627e98cd3ea11202ed5b2ebcadbf6ac2b4/.github/workflows/build-release.yml#L13-L19

@t-b Do you want to enable instrumentation for release branches as well? Otherwise, I would disable report generation for release branches.
