### ISSUE TITLE
Installer: Does not warn about all user manual installation in C:\Program Files\WaveMetrics\...

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#186]
IIRC we warn the user when a manuall installation is detected. But that seems to not include all user manual installations into `%ProgramFiles%` or?

Bug report from @timjarsky:
> Here is what happened: MIES was previously manually installed (by an administrator) for 
> all users. Then the installer was used to install for a user/account that did not have admin 
> privileges. The installer did not tell the user to first remove the manually installed copy of 
> MIES. (bearbeitet)

@MichaelHuth Is that correct?

**Comment by MichaelHuth** [comment]
I have looked into the installer code and currently different privileges are not mixed. 

So if you install as user (specifically this means 'not admin' !) then it checks if a uninstaller from a previous user mode installation of this user is present.

If you install as admin then it checks in the registry ifthe mies software package registered an uninstaller.


Generally a user can not install into %ProgramFiles% unless he has elevated rights.

What probably can be done is:

If a user installs I can try to check if an admin installation is present. If the user has the rights to read the appropriate registry keys. In non-silent mode I can call the uninstaller which most likely will popup an privilege elevation request. Another option would be to show a message box and abort installation.

In silent mode I abort installation silently.

If an admin installs, I can not see if one or more of the users might have MIES installed as MIES and the shortcuts to include everything in Igor Pro is all located inside the users personal folder.

**Comment by MichaelHuth** [comment]
@t-b @timjarsky See https://github.com/AllenInstitute/MIES/pull/191

In my tests it showed that there is no default functionality to popup UAC elevation request automatically if a user tries to run the uninstaller that requires admin rights.

**Comment by MichaelHuth** [comment]
I am still not 100% sure how the originally described error can come up. As thomas wrote, we have a second check before we start copying files. If in the target Igor procedures folder a file links e.g. to MIES_Include.ipf then we abort the installation with a message that there is a manual installation that has to be removed first. This check is done for the global Igor path and the local user folder for Igor Procedures. 

If there was a manual installed copy at the targetted Igor Pro the abort should have come up.

I will change the uninstall logic by the installer now to a try + recheck approach:

- The installer will register MIES in Add/Remove Programs depending on shell context now in HKLM or HKCU. The uninstaller is created with the same shell context.

- On startup the installer will check in HKLM and HKCU for uninstall information (and for compatibility in default user folder)

- The installer will call found uninstallers regardless of context.

- A second check is done if the registry entries were properly removed. If they are still there then a uninstallation with admin privileges is requested by message box and installation is aborted.

This will not solve the following problem: A user installs as user in his folder MIES. Afterwards an admin installs as admin MIES for All Users.

**Comment by MichaelHuth** [comment]
Ok I found something: The check if any of the lnk file targets in the Igor Procedures folder points to MIES_Include.ipf returns only the target if one has at least the same rights as the target file.
So it works for a User when he checks against his own `%DOCUMENTS%\WaveMetrics\Igor Pro 7 User Files\Igor Procedures` folder and it works also for an Admin checking against `%PROGRAMFILES%\Wavemetrics\Igor Pro 7 Folder\Igor Procedures`.
It does not work when a user attempts to check the latter.

At the same time it works when manually following the link in explorer...

This is not solved yet.

With the recent changes the installer always creates uninstall information in the registry. This makes it easier to see if an installation is present, such that the described case should only happen if this information is not present in the registry and  a 'manual' installation of a higher privilege is present.

While I think that the new approach is more robust it has a side effect:
If an installer created for user privilege was run as admin then a subsequent attempted User installation may run the uninstaller of the previous admin installation first, before the installer aborts.  In this case the uninstaller does nothing because of lacking rights, but it is interactive.

If the installer was created for admin privilege then the later uninstall.exe call from the user will abort the uninstaller immediatly.

**Comment by MichaelHuth** [comment]
I would like to add another thing, that is a windows peculiarity: If you attempt uninstall through `Add/Remove Programs` windows always asks for elevation. If you call `uninstall.exe` directly it does not.
