### ISSUE TITLE
TestNIAcquisitionReliability: Test failing with instrumentation in main

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#2069]
Failure: https://github.com/AllenInstitute/MIES/actions/runs/8302798808/job/22726821442

Introduced in 380c9b88 (bugfix: FIFO2WAVE does not work with single point ranges, 2024-03-06).

Can you reproduce the failure with instrumentation and expensive?

**Comment by MichaelHuth** [comment]
I think the problem here is that the CI machine seems to be too slow to finish the acquisition within 10 mins.

I can not reproduce the failure here.
With instrumentation and expensive the test runs here 402 s (2.49 acquisitions/s).

It is notable that the failing test on the CI runs 600.x s, which indicates that it hits the 10 min timeout after 581 acquired sweeps (0.96 acquisitions/s)
