### ISSUE TITLE
Avoid very long popup menues

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#228]
Very long popup menues are difficult to navigate. Currently there is no builtin support for auto grouping.

But Adam posted someting at https://www.wavemetrics.com/comment/18551#comment-18551 which works quite well.

![bandicam 2019-06-26 21-12-05-751](https://user-images.githubusercontent.com/1185677/60207819-15fd2880-9857-11e9-97b7-38d4a73a6653.jpg)

The names of the menu entries can be dynamic as well, this was done until 1f5693da (Always include MIES_TangoInteract, 2018-02-20) for the tango interact functionality.

The real problem to solve are the labnotebook entry lists for the databrowser. The two popup menues can also be changed to one.

**Comment by MichaelHuth** [comment]
@t-b So I found a crash in combination with the dynamical generated menus and reported it to WM.
I also found that `PopupContextualMenu/N/ASYN=Callback` does not work. It would be exactly the combination we would need though. The other /ASYN variants are not usable for dynamicly generated menus. I also wrote WM an email regarding this, since `PopupContextualMenu/N/ASYN=Callback` is not really documented and we could use that feat.

**Comment by t-b** [comment]
- [ ] Don't use GetCurrentWindow()
- [ ] Unify both popup menues for numerical and text

Extract 

```
   col = FindDimLabel(labnotebookValues, COLS, setting)

   if(col < 0)
	   return $""
   endif
```
from `GetNonEmptyLBNRows` into its own function and use that in DB_PopMenuProc_LabNotebook.

**Comment by MichaelHuth** [comment]
[ ] PEXT_SplitToSubMenus should take a wave, convert list to wave in button proc for default FuncRef
[ ] GetLabNotebookSortedKeys should return wave, as well as DB_GetLBTextualKeys/DB_GetLBNumericalKeys/DB_GetLBKeys
[ ] Change Analysisbrowser LBN_GetLBTextualKeys/LBN_GetLBNumericalKeys to use function that returns WAVE with keys, use TextWaveToList there
