### ISSUE TITLE
Add deconvolution to per pulse averaging and data/analysis browser

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#26]

**Comment by t-b** [comment]
Equation: https://elifesciences.org/articles/37349#equ2

**Comment by t-b** [comment]
There is also an example experiment in Igor for spectra deconvolution.

**Comment by t-b** [comment]
@timjarsky Matthias is looking for some good ESPs in a Igor pxp? Do you have one? If yes can you upload it to the FTP?

**Comment by timjarsky** [comment]
2018_06_05_123927-compressed.nwb is on its way. The connection is from 7->2

**Comment by ukos-git** [comment]
@timjarsky Thanks for the quick response.

I chose minimal algorithm for fixed tau from [Richardson/Silberberg](https://doi.org/10.1152/jn.00942.2007):

```igorpro
output = p < 1 ? 0 : tau * (source[p] - source[p - 1]) / DimDelta(source, 0) + source[p - 1]
```

![graph](https://user-images.githubusercontent.com/16167358/50373346-023de480-05de-11e9-97b1-467191d4d52c.PNG)

So in principal the algorithm is working. It deviations require some intermediate smoothing to get good results so I have added a panel element for it.
I had implemented the Reconvolution backcheck, but removed it, because it has basically not use. PA Panel now looks like this:
![panel](https://user-images.githubusercontent.com/16167358/50373382-af186180-05de-11e9-82f4-536f5e35c6d6.png)

Taken  `2018_06_05_123927-compressed.nwb` Sweep 71, AD10, HS2:

![average](https://user-images.githubusercontent.com/16167358/50373365-47621680-05de-11e9-92af-8872bb879305.PNG)
![deconv](https://user-images.githubusercontent.com/16167358/50373367-49c47080-05de-11e9-8bb2-9c2f8cf42bfe.PNG)

Not so sure if the implementation suits your working protocol. It should suffice for a first version but I'm open for further improvements.

**Comment by timjarsky** [comment]
@ukos-git Looks good! Could the time axis range be modified to show less post response baseline and more signal?

**Comment by ukos-git** [comment]
If it is only for the eye and not for serious analysis, I would recommend smoothig to get rid of the noise but too much smoothing could hide information, so I would add a slider or something similar to adjust the smoothing level.

**Comment by ukos-git** [comment]
@timjarsky sorry. You mean the time axis. Ok. Maybe a peak analysis and then a automatic axis pick around the found peaks?

**Comment by timjarsky** [comment]
@ukos-git https://github.com/AllenInstitute/MIES/issues/26#issuecomment-451414084 good idea!

@ukos-git https://github.com/AllenInstitute/MIES/issues/26#issuecomment-451414559 What do you think about defaulting to ~10 ms after the pulse start time and providing a setvariable for the user to adjust the x-axis time window?

One more point to consider: ideally this feature would be used during data acquisition and without slowing it down substantially. No need to address this yet. I should test it out first and identify if there are any bottle necks of significance.

**Comment by ukos-git** [comment]
@timjarsky 
Just a quick suggestion:

![screenshot from 2019-01-17 18-19-54](https://user-images.githubusercontent.com/16167358/51396652-c5fb9680-1b3f-11e9-8e5b-c05ea19975e8.png)
![screenshot from 2019-01-17 18-20-05](https://user-images.githubusercontent.com/16167358/51396653-c5fb9680-1b3f-11e9-8894-42e124c4895c.png)

The two images above show Smoothing of 500 and 1000.
Smoothing to 1000 possibly removes information.

**Comment by timjarsky** [comment]
@ukos-git Thanks for checking the effect of the larger smoothing values I'm suggesting. I think I'd still like to stick with 1000 for now;  I'm not so concerned about the signal loss shown in the examples above and I think lower smoothing values increase the chance that a user will confuse noise for a signal. In testing, I also noted the time constant had a powerful effect on the amplitude. So, my plan is to implement an automated measurement of the time constant. Once we have this, we can circle back to see if we can optimize the smoothing guess/default based on the measured time constant. Does this sound reasonable?

**Comment by ukos-git** [comment]
Ok. I did not notice such high effects regarding the time constant. 
I think there was a fitting routine for the time constant in one of the papers. A fit would only make sense for a good dataset, though and that should probably be user-triggered.

**Comment by timjarsky** [comment]
@ukos-git To my eyes, the effect of a 30 ms delta on time constant would be important for our users.
10 ms
![image](https://user-images.githubusercontent.com/5693697/51409406-971cfa80-1b16-11e9-8e06-9bb4674dc373.png)
40 ms
![image](https://user-images.githubusercontent.com/5693697/51409433-a4d28000-1b16-11e9-97a7-48f907f7d9f5.png)

In a separate PR, I'd like to adapt the TargetV analysis function so that it writes the time constant of each neuron to the lab notebook.  The timeconstant, could be read from the labnotebook and used for deconvolution, if triggered by the user. A key point is that each headstage would have it's own tau. Do you see any issue with merging as is and adapting later to a per HS tau (that's pulled from the LBN)?

One minor change request: set the line thickness of the deconvolution to 2 point and make all the traces black.

**Comment by t-b** [comment]
Closed via PR.
