### ISSUE TITLE
SweepFormula: Handle plotting of `one vs all` better

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#286]
Something like

```
range(0,10) vs
 [range(0,10), range(10,20)]
```

should plot the first formula against each column of the second formula.

Something like

```
[range(0,10), range(10,20)] vs
 [range(0,10), range(10,20)]
```

would plot `range(0,10) vs range(0,10)` and `range(10,20) vs range(10,20)`. In this case we don't support a mismatch of the columns on the  lhs vs rhs.

**Comment by t-b** [comment]
One vs All:

```
max(
	data(cursors(A, B),
	channels(DA0),
	[0])
)

 vs

min(
	data(cursors(A, B),
	channels(AD0),
	sweeps())
)
```

All vs One (first example flipped):

```
min(
	data(cursors(A, B),
	channels(AD0),
	sweeps())
)

vs

max(
	data(cursors(A, B),
	channels(DA0),
	[0])
)
```

**Comment by timjarsky** [comment]
@t-b Shouldn't one vs all have all channels of a type on one side of the vs?

e.g., 
```
max(
	data(cursors(A, B),
	channels(DA0),
	[0])
)

 vs

min(
	data(cursors(A, B),
	channels(AD),
	sweeps())
)
```

**Comment by t-b** [comment]
@timjarsky Yes that will be supported as well.

**Comment by ukos-git** [comment]
We should not mix column-centric and row-centric data layouts here. Otherwise, the whole concept gets fuzzy.

Our data is located in the rows. If we have 2 columns, this means, we have two datasets where the data of each set is in the rows of the wave.

Your example `range(0,10) vs  [range(0,10), range(10,20)]` looks like this:

![Screenshot from 2019-09-24 18-04-22](https://user-images.githubusercontent.com/16167358/65529137-e0b7b380-def5-11e9-943b-810716d49f50.png)

This means that your y dataset has 2 points each per dataset and contains 10 entities. You are plotting it against a 1-dimensional dataset of 10 points which gives 10 traces where 2 points are plottet against 10 points.

A typical return from the data() function is row-centric. 

![Screenshot from 2019-09-24 18-29-06](https://user-images.githubusercontent.com/16167358/65531030-51140400-def9-11e9-910e-aadd2455002f.png)

This is 8 data objects along the columns and data distributed along the rows. This can be simulated with the range function but is a bit hacky right now, as we do not have an iteration operation.

> `range(0,10) vs  [range(0,10), range(10,20)]`

In your example is plotting a data entry of 10 points against 10 data entries of 2 points. It is effectiveley the same as `range(2) vs  [range(0,10), range(10,20)]`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65529599-b9151b00-def6-11e9-8903-932d7b5279f7.png)

If you want to simulate sweeps, you have to place data entities along the rows, which is a bit hacky with column-based arrays but let's simulate an exemplary data output of 10 sweeps:

`[range(0,10), range(2,12), range(4,14), range(6,16)]`

![Screenshot from 2019-09-24 18-40-26](https://user-images.githubusercontent.com/16167358/65531728-d51abb80-defa-11e9-8c62-bcd2f451ca76.png)

plotting this gives

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65531456-31311000-defa-11e9-88e3-8edff6434f7b.png)

Let's assume an exemplary dataset with 10 sweeps and 4 data points per sweep along the time axis as

`[range(10), range(10,20), range(10), range(10,20)]`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65532369-fc25bd00-defb-11e9-929a-5735da5e2d7e.png)

If I understand you correctly, you want to plot y[][i] vs x[][i] in general indicating **many to many**.
As data is always aligned in the rows but the column can be 1 to indicate a **many to one** or **one to many** display format depending on whether it is the x-wave or the y-wave that has a column of 1.


### one to many

`range(4) vs [range(10), range(10,20), range(10), range(10,20)]`

it should plot the 10 traces (sweeps have 4 data points): always the same y against each dataset of x.

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65533189-799dfd00-defd-11e9-9d4a-680ce3a677fd.png)

`range(10) vs [range(10), range(10,20), range(10), range(10,20)]`

If the first wave is greater than the second, you need Igor's `SetAxis/A=2` otherwise it will look like this:

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65533318-abaf5f00-defd-11e9-8e94-041b7ebcaab6.png)

This then allows to use the time function for plotting.

`time(setscale(range(4),x,1,0.1)) vs [range(10), range(10,20), range(10), range(10,20)]`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65533695-70f9f680-defe-11e9-9a72-96cb946d8114.png)

### many to one

`[range(10), range(10,20), range(10), range(10,20)] vs range(4)`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65534298-6d1aa400-deff-11e9-86e9-1f0b267d27d8.png)

`[range(10), range(10,20), range(10), range(10,20)] vs range(3)`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65534334-7a379300-deff-11e9-9150-942192cfbb3e.png)

`[range(10), range(10,20), range(10), range(10,20)] vs range(2)`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65534360-87ed1880-deff-11e9-9128-64ad4f301fb5.png)

### one to one

`range(10) vs range(10)`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65534033-05645900-deff-11e9-9bf7-97e5888ca5cc.png)

### many to many

`[range(10), 2* range(10)] vs [range(10), range(10)]`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65534161-35136100-deff-11e9-8a57-db7ad171380e.png)

`[range(10), 2 * range(10)] vs [range(0,10), range(10,20)]`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65528287-620e4680-def4-11e9-89f5-ff12cf38ba2b.png)

**Comment by ukos-git** [comment]
## zero vs 1 dimension

### one to many

`1 vs range(5)`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65536126-14e5a100-df03-11e9-8e40-3d9a2a2ebb9a.png)


### many to one

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65536160-27f87100-df03-11e9-9754-f66a0238e05b.png)

### many to many

`range(5)*range(5) vs range(5)`

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65536209-42324f00-df03-11e9-8e69-72052f699d69.png)

**Comment by ukos-git** [comment]
```
max(
	data(cursors(A, B),
	channels(DA0),
	[0])
)

 vs

min(
	data(cursors(A, B),
	channels(AD),
	sweeps())
)
```

currently gives

![FormulaPlot](https://user-images.githubusercontent.com/16167358/65537673-f2a15280-df05-11e9-9aa1-65bd4a546ffd.png)

**Comment by t-b** [comment]
Fixed in 302111a1.

**Comment by ukos-git** [comment]
I secured the above behavior with unit tests in ec0a1758547d60605b091dbbe029caadeda80a02

**Comment by t-b** [comment]
An example file is on the FTP "potentially_mixed_AD_chan_in_SF.pxp". The user wants to have separate traces for the channels.

**Comment by t-b** [comment]
Reopening as it is not resolved yet, https://github.com/AllenInstitute/MIES/issues/286#issuecomment-535152733.
