### ISSUE TITLE
PulseAveraging: Removing a HS in OVS from a sweep lets the plot ignore the associated channel only.

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#729]
Currently when setting in OVS a HS to removed from a sweep then only the associated channel is removed from the plot (i.e. on the horizontal). However other HS still see the removed HS (on the vertical) and there is no change.

@timjarsky Is it intentional (in respect to the data analysis) that there is in the vertical direction no change? If I would see the whole plot similar to a cross correlation I would expect a change in horizontal as well as vertical?

**Comment by timjarsky** [comment]
@MichaelHuth Are you asking if headstage removal (in OS) is being used, what happens to data on other headstages from the same sweep?

If yes, in the PA plot, the corresponding data from the same sweep on other headstages should also be removed.

In the data browser, I think we want to give the user to remove the corresponding data. For our experimental use case, we want the corresponding data removed because they are related, but I can envision use cases where data on different headstages is only related in time.

Does that make sense?

**Comment by t-b** [comment]
> If yes, in the PA plot, the corresponding data from the same sweep on other headstages should also be removed.
We are currently not removing in main either. So this is something to follow up on after we have merged the current PA plot work.
