### ISSUE TITLE
Missing sweep data and sweep config data in MIES Data Browser 

### ISSUE THREAD

**Issue by ru57y34nn** [AllenInstitute/MIES#889]
I have uploaded a few example pxp files to the FTP server which are missing sweep data:

 - Crh-IRES-Cre_ZJH;Sst-IRES-FlpO;Ai65-543820.05.02.01.pxp is missing sweep data and sweep config data for sweeps 0-48 in the MIES Data Browser.
 - Rbp4-Cre_KL100;Ai14-543835.09.09.02.pxp is missing sweep data and sweep config data for sweeps 0-8 in the MIES Data Browser.
 - Ctgf-T2A-dgCre;Ai14-544135.11.06.01.pxp is missing sweep data and sweep config data for sweeps 0-1 in the MIES Data Browser.

It appears that the rig operator had used the sweep rollback function at certain points during these experiments but it is unclear to me if this was the cause of the issue. I know that I had previously raised a similar issue that was related to a bug in the sweep rollback function that has since been fixed. These experiments were collected back in mid-September of 2020 so it is possible that this is the same issue and that these were collected before it was fixed.

**Comment by t-b** [comment]
That looks like the same bug. The sweeprollback bug was fixed in 03c94d2a (Merge pull request #743 from AllenInstitute/bugfix/sweep-rollback-backport, 2020-11-20) in the release/2.1 branch.

I'll see if we can recover some of them from the databrowser `X_xxx` folders.

**Comment by t-b** [comment]
So I've started diving into that. All results are preliminary.

- 'Rbp4-Cre_KL100;Ai14-543835.09.09.02.pxp': All sweeps can be reconstructed
- 'Crh-IRES-Cre_ZJH;Sst-IRES-FlpO;Ai65-543820.05.02.01.pxp': All sweeps can be reconstructed
- 'Crh-IRES-Cre_ZJH;Sst-IRES-FlpO;Ai65-543820.05.02.01.pxp': Sweeps 2-47 can be reconstructed, 0 and 1 are lost

The linked PR has the code for reconstruction. We can do the reconstruction because we had 1D waves for each channel for display purposes lying around.

I would provide reconstructed PXPs once that PR is in its final state.

Do you have more PXPs with missing sweeps? If yes do these also include TTL channels? I don't have TTL channels implemented yet.

**Comment by timjarsky** [comment]
@t-b IVSCC doesn't use TTL. It's okay to postpone TTL recovery until it's needed.

**Comment by t-b** [comment]
@timjarsky Thx. It was much less work than anticipated so I've already included TTL support. And also unassociated channels now work.

**Comment by t-b** [comment]
The code in #920 should be ready once CI passes.
