### ISSUE TITLE
NI DAQ fails due to index out of range error

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#95]
Reproduced in master with [HardwareTests.pxp.gz](https://github.com/AllenInstitute/MIES/files/2626439/HardwareTests.pxp.gz).

Use the stimset `PSQ_DaScale_Sub_DA_0` and try to acquire data. It does not work.

It breaks in line 1049ff in MIES_DataConfiguratorITC.ipf:

```
NIChannel[insertStart[i], insertStart[i] + setLength[i] - 1] =                     \
limit(                                                                                         \
DAGain[i] * DAScale[i] * singleStimSet[decimationFactor * (p - insertStart[i])][setColumn[i]], \
NI_DAC_MIN,                                                                                    \
NI_DAC_MAX); AbortOnRTE
```

If I subtract another `1` in the parantheses `(p - insertStart[i] - 1)` it works so it looks like the decimationFactor is still buggy.

**Comment by t-b** [comment]
Maybe we should just use limit(...) for the row index of singleStimSet?

**Comment by MichaelHuth** [comment]
In principle the decimation works here, however the problem is that Igor does a round on the fractional indice and not a trunc.

In the example the decimationfactor is 0.4, stimSet is 720000 and NIChannel is 1810000 with a insertStart of 10000. So 720000/1800000 = 0.4
Now running over p splits the 720000 in units of 0.4 size and thus the last value reached is 719999.6.

Igor round that to 720000 which causes the error.

I suggest to add a trunc(decimationFactor * (p - insertStart[i])) to prevent that the rounding goes to values beyond the limit.

**Comment by t-b** [comment]
@MichaelHuth Sounds good. Could you make a MR? I think we want to have `trunc` for ITC hardware as well or?

**Comment by MichaelHuth** [comment]
@t-b For ITC the decimationFactor never goes < 1 due to the definition of the standard sample rate for the generators. So the left side of the assignment always has a index range for p that is smaller/equal than the stimSet length.

This means the decimationsFactor splits the stimSet always in units >= 1, such that DimSize(stimSet[x], ROWS) - decimationFactor is always <= DimSize(stimSet[x], ROWS) - 1.

**Comment by t-b** [comment]
@MichaelHuth I see. Thanks for the clarification.

**Comment by t-b** [comment]
Fixed in PR 1033.
